# Generated by Django 3.2.4 on 2021-07-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restocart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
